#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 08 23:10:56 EST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim relu_tb_behav -key {Behavioral:sim_1:Functional:relu_tb} -tclbatch relu_tb.tcl -log simulate.log"
xsim relu_tb_behav -key {Behavioral:sim_1:Functional:relu_tb} -tclbatch relu_tb.tcl -log simulate.log

