#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< HEAD
# Generated by Vivado on Tue Nov 03 19:25:40 EST 2020
=======
# Generated by Vivado on Tue Nov 03 19:00:06 EST 2020
>>>>>>> fa1e642ddb41decf7eceabb40de06268ef5c91b4
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim neuron_tb_behav -key {Behavioral:sim_1:Functional:neuron_tb} -tclbatch neuron_tb.tcl -log simulate.log"
xsim neuron_tb_behav -key {Behavioral:sim_1:Functional:neuron_tb} -tclbatch neuron_tb.tcl -log simulate.log

