#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 09 00:17:00 EST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim neural_network_tb_behav -key {Behavioral:sim_1:Functional:neural_network_tb} -tclbatch neural_network_tb.tcl -view /home/minimario/Documents/6.111/ml_fpga/project_1/neural_network_tb_behav.wcfg -log simulate.log"
xsim neural_network_tb_behav -key {Behavioral:sim_1:Functional:neural_network_tb} -tclbatch neural_network_tb.tcl -view /home/minimario/Documents/6.111/ml_fpga/project_1/neural_network_tb_behav.wcfg -log simulate.log

